### ISSUE TITLE
Possible to send negative value to strings.Repeat

### ISSUE THREAD

**Issue by dcarbone** [shenwei356/stable#1]
This check is prudent: https://github.com/shenwei356/stable/blob/33c2ccf83610a584d8ef40dc77e091c3738e254d/table.go#L751-L756

However, the value of `lenText` can be modified below this check:

https://github.com/shenwei356/stable/blob/33c2ccf83610a584d8ef40dc77e091c3738e254d/table.go#L759-L762

This can cause `lenText` to be greater than `width`, which causes issues in the output block:
https://github.com/shenwei356/stable/blob/33c2ccf83610a584d8ef40dc77e091c3738e254d/table.go#L764-L776

I'm not entirely certain what the purpose of `lenText += strings.Count(text, "\t")` is, given that the below replace statement simply replaces tabs with a single space.

I was thinking perhaps a configurable field to allow specifying desired printable width of tab characters, then moving that logic _before_ the `runewidth.StringWidth(text)` check?

**Comment by shenwei356** [comment]
> I'm not entirely certain what the purpose of lenText += strings.Count(text, "\t") is, given that the below replace statement simply replaces tabs with a single space.

Will change the order.

> I was thinking perhaps a configurable field to allow specifying desired printable width of tab characters,

Yes, `\t`, `\r`, `\n`, `\b` should all be replaced with something, Users can specific each replacement and a default map should also be available.

>  then moving that logic before the runewidth.StringWidth(text) check?

OK

**Comment by shenwei356** [comment]
Added a Method for this.

```go
// Convert uses a custom map to replace the DefaultConversionTable for converting special characters.
func (t *Table) Convert(m map[string]string) *Table {
```

And the default table is 

```go
var DefaultConversionTable = map[string]string{
	"\t": "    ",
	"\r": "",
	"\n": " ",
	"\v": " ",
	"\f": " ",
	"\a": "",
	"\b": "",
}
```

**Comment by shenwei356** [comment]
I will make a small change: converting a "\t" to one space (same as the previous behaviour).

    "\t": " ",

**Comment by shenwei356** [comment]
available in v0.2.0.

**Comment by dcarbone** [comment]
Excellent, thank you!

Unfortunately I no longer work for the company where I wrote the tool that uses this lib (things happen quick!), so I won't be able to effectively test the changes :(

**Comment by shenwei356** [comment]
Don't worry, tell me if you met some things.

And good luck!
